# Generated by Django 5.0 on 2023-12-14 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('FEN', models.CharField(max_length=200)),
                ('moves', models.CharField(max_length=200)),
                ('rating', models.IntegerField()),
                ('rating_dev', models.IntegerField()),
                ('popularity', models.IntegerField()),
                ('Nb_plays', models.IntegerField()),
                ('themes', models.CharField(max_length=200)),
                ('game_url', models.CharField(max_length=200)),
                ('openning_tags', models.CharField(max_length=200)),
            ],
        ),
    ]
